### ISSUE TITLE
Usage of checkGenes

### ISSUE THREAD

**Issue by DarioS** [DavisLaboratory/singscore#25]
I see a number of warnings like:

```r
Warning messages:
1: In checkGenes(upSet, rownames(rankData)) :
  4 genes missing: MAS1, AGTR2, KNG1, CYP11B2
```

I would like to find out how to use `checkGenes` at the command line and I try `?checkGenes` but there is an error "No documentation for ‘checkGenes’ in specified packages and libraries". Should it be used by the end-user?

**Comment by bhuvad** [comment]
Hi @DarioS,

Before I discuss this, I would like to point out that warnings are not an issue in most R packages. In our case, we warn users that some of the genes in the gene-set may not be measured in their dataset therefore they will be dropping them from the analysis. We need to make users aware of this information as we will be processing a modified version of their original data. This does not mean the analysis will be halted. The `checkGenes()` function is an internal function of the package that simply performs this task of discarding unmeasured genes and notifying the users. Since this is an internal function, we expect end-users to not use it directly, however, if you need to use it you can call it using `singscore:::checkGenes()` (this is the syntax for calling any internal function in R). I hope this helps.

Cheers,
Dharmesh
