### ISSUE TITLE
generateNull() function used with multiScore()

### ISSUE THREAD

**Issue by shadihames** [DavisLaboratory/singscore#36]
Hi, I was wondering if there was a way of determining p values for an output run using multiScore(). It doesn't seem like you can input a GeneSetCollection object into generateNull(), just a GeneSet object. So if I use multiScore() to run through multiple genesets, do I have to run each of those gene sets separately through generateNull()?

Thanks!

**Comment by bhuvad** [comment]
Hi,

You would have to run this for each gene-set independently. The reason here is the computational demand for so many tests. We would generally advise you not to run such a test unless necessary. It is also important to note that the permutation test is testing whether the score is significantly different from 0. Often, when you are scoring across multiple gene-sets, you will be interested in a comparative assessment (i.e., what gene-sets are enriched). In such a case, testing significant differences from 0 are unimportant and you would rather compare the scores and rank gene-sets. These reasons motivated us to NOT implement a significance test for multiple gene-sets. I hope this helps.

Cheers,
Dharmesh
