### ISSUE TITLE
Significance of scores

### ISSUE THREAD

**Issue by faraz89** [DavisLaboratory/singscore#37]
Hi,

Is there a way to calculate p-value to check if the scores are significantly different between two samples? I don't mean the Null distribution pvalue but the pvalue between samples to check if there is a significant difference between the given samples in terms of scores.

Thanks,
Faraz

**Comment by bhuvad** [comment]
Hi Faraz,

This is not really feasible since you would not know what the distribution of each of the samples would be. If instead, you were looking at two populations of samples, you may be able to run a non-parametric test such as the Mann–Whitney U test to test differences in scores between the two populations.

Cheers,
Dharmesh
