### ISSUE TITLE
SimpleScore() Output Interpretation

### ISSUE THREAD

**Issue by xyang2uchicago** [DavisLaboratory/singscore#42]
I'm currently using your fantastic package and appreciate your responsiveness.
I'm trying to understand the output of the simpleScore() function, specifically the scale used for the scores (log2 or log10).
For instance, in the demonstrated output (https://f1000research.s3.amazonaws.com/manuscripts/22970/08651dce-c3b9-4f98-8cb0-dddcc8d5aa4d_figure4.gif), I'd like to determine if the first original box score is significantly higher than the first green box score.

To assess this, I understand I need to consider both the p-value and the fold change. However, I'm unsure about the interpretation level of these scores (log2 or log10).
Could you clarify the scale used for the scores returned by simpleScore()?
Thank you for your continued support.
HOlly

**Comment by bhuvad** [comment]
Hi Holly,

Sorry for the delay in responding to you. The scores are not in a log scale. The scores are obtained through computing the mean of ranks of all genes, and this value is then normalised in the range of -0.5 and 0.5. Positive scores mean that genes in the signature are expressed above the average expression of all genes and vice versa (see schematic diagram below). To compare scores between groups, you then need to perform a t-test (ideally the non-parametric such as the Mann-Whitney U test for independent samples or the Wilcoxon signed rank test for paired samples). I emphasise again that the difference in scores is a relative difference and is not an indication of absolute fold changes because we are working with ranked expression instead of the raw gene expression. As genes do not work independently, the collective logFC of a gene expression signature cannot be well estimated from the expression data alone therefore you will often see relative differences in signature activity reported.

![Singscore schematic](https://github.com/user-attachments/assets/8fc70013-383e-4bb1-bfb4-a760d9936e38)


Cheers,
Dharmesh
